name: fetch-linguist
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  fetch:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Fetch YAML
      run: curl https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml > linguist.yml
    - name: Convert to JSON
      uses: fabasoad/data-format-converter-action@main
      id: yaml2json
      with:
        input: 'linguist.yml'
        from: 'yaml'
        to: 'json'
    - name: Save result
      run: echo -e ${{ toJson(steps.yaml2json.outputs.output) }} > linguist.json
    - name: Commit changes
    # https://github.com/orgs/community/discussions/26560
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add linguist.yml linguist.json
        git diff-index --quiet HEAD || git commit -m "Update data"
        git push
