name: fetch-linguist
on: push
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Fetch YAML
      run: curl https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml > linguist.yml
    - name: Convert to JSON
      uses: fabasoad/data-format-converter-action@main
      id: yaml2json
      with:
        input: 'linguist.yml'
        from: 'yaml'
        to: 'json'
    - name: Save result
      run: echo -e ${{ toJson(steps.yaml2json.outputs.output) }} > linguist.json
    - name: Count languages
      uses: sergeysova/jq-action@v2
      id: jqcount
      with:
        cmd: 'jq length linguist.json'
    - name: Update linguist.json count
      uses: jossef/action-set-json-field@v2.1
      with:
        file: linguist.json
        field: __count
        value: ${{ steps.jqcount.outputs.value }}
    - name: Commit changes
      id: commit
    # https://github.com/orgs/community/discussions/26560
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions"
        git add linguist.yml linguist.json
        git diff-index --quiet HEAD || git commit -m "Update data"
        git diff-index --quiet HEAD || echo "diff=true" >> $GITHUB_OUTPUT
        git push

  test: 
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - name: test2
      run: "echo ${{ needs.build.outputs.diff }}"

  deploy:
    runs-on: ubuntu-latest
    needs: fetch
    if: needs.fetch.outputs.diff != null
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x' 
    - name: Build app
      run: | 
        npm install
        npm run build
    - name: Commit changes
    # https://gist.github.com/tduarte/eac064b4778711b116bb827f8c9bef7b
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions"
        git add dist && git commit -m 'adding dist subtree'
        git subtree split --prefix dist -b gh-pages 
        git push -f origin gh-pages:gh-pages 
        git branch -D gh-pages 

